apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: 12factorapp
    chart: 12factorapp-1.0.0
    heritage: Tiller
    release: an12factorappv1
  name: an12factorappv1-12factorapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 12factorapp
      release: an12factorappv1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: 12factorapp
        release: an12factorappv1
    spec:
      containers:
      - image: mycluster.icp:8500/default/12factorapp:master-153
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9082
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: 12factorapp
        ports:
        - containerPort: 9082
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9082
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
